/** Generated by YAKINDU Statechart Tools code generator. */
package hu.bme.mit.yakindu.analysis.example;

import hu.bme.mit.yakindu.analysis.IStatemachine;
import hu.bme.mit.yakindu.analysis.ITimerCallback;

public interface IExampleStatemachine extends ITimerCallback,IStatemachine {
	public interface SCInterface {
	
		public void raiseStart();
		
		public void raiseElsoJon();
		
		public void raiseMasodikJon();
		
		public long getElsoJataekosIdeje();
		
		public void setElsoJataekosIdeje(long value);
		
		public long getMasoikJataekosIdeje();
		
		public void setMasoikJataekosIdeje(long value);
		
	}
	
	public SCInterface getSCInterface();
	
}
